import Head from 'next/head'
import Homelayuot from "../components/homelayout";
import Hero from "../components/Hero/hero";
import Advan from "../components/advan/advan"
import Services from "../components/Services/services";
import Form from "../components/Form/form";
import Description from "../components/Description/description";
import Work from "../components/work/work"

export default function Home() {
    return (
        <>
            <Head>
                <title>PORTER || TAXI </title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport"
                      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
                <meta httpEquiv="X-UA-Compatible" content="ie=edge"/>
                <meta name="yandex-verification" content="3f03b3a4f8d68231"/>
                <meta
                    name="description"
                    content="
           Переезжаете?
            ◾️ТОГДА С НАС ТРАНСПОРТ С ОПЫТНЫМ ВОДИТЕЛЕМ И ПОМОШНИКИ В ГОРОДЕ БИШКЕК

            ◾️Грузовые перевозки по низкой цене


  Вызвать"
                />
                {/*<meta name="google-site-verification" content="t8PlfNjYh7Rxau1mSPzvx4MRPE7ksOX8a3bkUtNIHew"/>*/}
                {/*<script async src="https://www.googletagmanager.com/gtag/js?id=UA-223440086-1">*/}
                {/*</script>*/}

                <meta charSet="utf-8"/>
                <meta name="keywords" content="Грузо-Express,
               Надёжная и бережная доставка,
             5 лет опыта работы,
           На месте когда и где нужно,
            Саблюдаем дорожные правила и этикет.
         "/>
            </Head>

            <Homelayuot>
                <Hero/>
                <Advan/>
                <Services/>
                <Work/>
                <Form/>
                <Description/>
            </Homelayuot>

        </>
    )
}
